### ISSUE TITLE
JSON::GeneratorError - source sequence is illegal/malformed utf-8:

### ISSUE THREAD

**Issue by sahilchopra** [humante/redis-browser#30]
Hi 

I am getting following error when click on any key

Any idea how it can be fixed?

Thanks

Logs

**/home/jc-cm-lptp-09/.rvm/gems/**ruby-2.3.1@cms/gems/redis-browser-0.5.1/lib/redis-browser/web.rb:46:in `block in <class:Web>'****

**Started GET "/browser/key.json?connection=default&key=session%3A3966592760c86ebeceaee8c3f0014ff2"** for 127.0.0.1 at 2017-01-12 15:12:23 +0530
2017-01-12 15:12:23 - JSON::GeneratorError - source sequence is illegal/malformed utf-8:
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `to_json'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:34:in `to_json_with_active_support_encoder'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:57:in `to_json'
	/home/jc-cm-lptp-09/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	/home/jc-cm-lptp-09/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/json/common.rb:224:in `generate'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:101:in `stringify'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:35:in `encode'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/activesupport-4.2.7.1/lib/active_support/json/encoding.rb:22:in `encode'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/multi_json-1.12.1/lib/multi_json/adapters/json_common.rb:19:in `dump'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/multi_json-1.12.1/lib/multi_json/adapter.rb:25:in `dump'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/multi_json-1.12.1/lib/multi_json.rb:139:in `dump'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:113:in `block in resolve_encoder_action'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:112:in `each'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:112:in `resolve_encoder_action'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:98:in `json'
	/home/jc-cm-lptp-09/.rvm/gems/ruby-2.3.1@cms/gems/redis-browser-0.5.1/lib/redis-browser/web.rb:46:in `block in <class:Web>'

**Comment by andre8888** [comment]
i have the same problem

**Comment by sahilchopra** [comment]
Fixed version 
gem 'redis-browser', github: 'sahilchopra/redis-browser'

**Comment by andre8888** [comment]
@sahilchopra works great! Thanks for the fix!

**Comment by szajbus** [comment]
I'm hesistant to merge in the fix because it relies on `Marshal.load` which should not be used to load user-provided data.

@sahilchopra @andre8888 
Can you please provide the value you hold in redis that is causing the problem? Maybe we can come up with a better fix for this issue that way.

**Comment by sahilchopra** [comment]
Hi Michal
I am trying to access session from redis (set by devise gem). 

Let me know if you need any more information. 
Thanks 
S

**Comment by stuarthannig** [comment]
+1 getting same error, can't view the value of key.

The value is HTML, we're using Redis as a page cache and have Rails taking care of the cache store.

Sidenote: The redis-browser prints the value as HTML, doesn't escape.

**Comment by Infusible** [comment]
`http://my.domain.com/ -> /key.json?connection=default&key=betsPerHour%3A*
2018-05-24 13:02:33 - Encoding::InvalidByteSequenceError - "\xD0" on US-ASCII:
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `encode'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `to_json'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `dump'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:25:in `dump'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:113:in `block in resolve_encoder_action'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:112:in `each'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:112:in `resolve_encoder_action'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:98:in `json'
	/usr/local/bundle/gems/redis-browser-0.5.1/lib/redis-browser/web.rb:42:in `block in <class:Web>'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `[]'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:971:in `forward'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1055:in `route_missing'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1006:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1002:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
2018-05-24 13:02:33 - Encoding::InvalidByteSequenceError - "\xD0" on US-ASCII:
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `encode'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `to_json'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapters/json_common.rb:19:in `dump'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:25:in `dump'
	/usr/local/bundle/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:113:in `block in resolve_encoder_action'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:112:in `each'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:112:in `resolve_encoder_action'
	/usr/local/bundle/gems/sinatra-contrib-2.0.1/lib/sinatra/json.rb:98:in `json'
	/usr/local/bundle/gems/redis-browser-0.5.1/lib/redis-browser/web.rb:42:in `block in <class:Web>'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `[]'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:971:in `forward'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1055:in `route_missing'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1006:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1002:in `route!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'
	/usr/local/bundle/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/null_logger.rb:9:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
	/usr/local/bundle/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
	/usr/local/bundle/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
	/usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
	/usr/local/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
	/usr/local/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'`
